/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 85

    light.min_ratio: 0.01
    light.min_fill_ratio: 0.6 
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    # target_frame: camera_switch
    target_frame: odom
    max_armor_distance: 15.0

    ekf:
      sigma2_q_xyz_max: 3.0
      sigma2_q_xyz_min: 1.0
      sigma2_q_yaw_max: 6.0
      sigma2_q_yaw_min: 3.0
      sigma2_q_r: 40.0

      r_xyz_factor: 6e-4
      r_yaw: 8e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 0.8

      tracking_thres: 5
      lost_time_thres: 1.0

